apiVersion: v1
kind: Service
metadata:
  name: service-parkingapp
  labels:
    servicelabel: parkingappservice
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    apptemplate: template-parkingapp